name: Run Jest

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Run Server and Client Tests
        run: |
          mkdir -p logs

          node --experimental-vm-modules node_modules/jest/bin/jest.js \
            --silent=false \
            --config jest/jest.config.cjs > logs/tmp.log

          node --experimental-vm-modules node_modules/jest/bin/jest.js \
            --silent=false \
            --config jest/jest.frontend.config.cjs >> logs/tmp.log

          grep -E '^(PASS|FAIL)' logs/tmp.log \
            | sed 's|PASS|✔|' \
            | sed 's|FAIL|✘|' \
            | sed 's|.*\\tests/||' \
            > logs/test-summary.txt

      - name: Send summary to Discord
        if: always()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          summary=$(cat logs/test-summary.txt)
          emoji="✅"
          status="Tests Passed"

          if echo "$summary" | grep -q '✘'; then
            emoji="❌"
            status="Tests Failed"
          fi

          msg="$emoji $status\n\`\`\`\n$summary\n\`\`\`"

          curl -X POST \
            -H "Content-Type: multipart/form-data" \
            -F "payload_json={\"content\": \"$msg\"}" \
            -F "file=@logs/test-summary.txt;type=text/plain" \
            "$DISCORD_WEBHOOK_URL"